{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-blueprint.configMapName" . }}
  labels:
    {{- include "app-blueprint.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ tpl ($value | toString) $ | quote }}
  {{- end }}
{{- end }}

