{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app-blueprint.fullname" . }}-migration
  labels:
    {{- include "app-blueprint.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    {{- if .Values.migration.hook.enabled }}
    helm.sh/hook: {{ .Values.migration.hook.events | quote }}
    helm.sh/hook-weight: {{ .Values.migration.hook.weight | quote }}
    helm.sh/hook-delete-policy: {{ .Values.migration.hook.deletePolicy | quote }}
    {{- end }}
    {{- with .Values.migration.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: {{ .Values.migration.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.migration.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        {{- include "app-blueprint.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "app-blueprint.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migration
          image: {{ include "app-blueprint.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.migration.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.migration.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if eq (include "app-blueprint.hasEnvFrom" .) "true" }}
          envFrom:
            {{- if .Values.configMap.create }}
            - configMapRef:
                name: {{ include "app-blueprint.configMapName" . }}
            {{- end }}
            {{- if or .Values.secret.create .Values.secret.existingSecret }}
            - secretRef:
                name: {{ include "app-blueprint.secretName" . }}
            {{- end }}
            {{- with .Values.envFrom }}
            {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.migration.resources | nindent 12 }}
{{- end }}

