{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-blueprint.secretName" . }}
  labels:
    {{- include "app-blueprint.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.stringData }}
  {{ $key }}: {{ tpl ($value | toString) $ | quote }}
  {{- end }}
{{- end }}

